=== pkoeker-riser/guibuilder/GuiBuilder/guivalues.dtd
<?xml version='1.0' encoding='iso-8859-1'?>
<!--
# Author: Peter Köker
# Version: 0.9.3
# Date: 25.11.2001
DTD fuer das Lesen und das Setzen von Werten der Fenster.
-->

<!ELEMENT Panel ((Panel | Component | Tree | Table)*)>
<!ATTLIST Panel
name	CDATA #REQUIRED
_oid	CDATA	#IMPLIED
>

<!ELEMENT Component (#PCDATA)>
<!ATTLIST Component
name	CDATA #REQUIRED
type	CDATA	#REQUIRED
_oid	CDATA	#IMPLIED
modified	CDATA	#IMPLIED
>

<!ELEMENT Tree (Node*)>
<!ATTLIST Tree
name	CDATA #REQUIRED
type	CDATA	#REQUIRED
_oid	CDATA	#IMPLIED
>

<!ELEMENT Node ((Panel? | Node)*)>
<!ATTLIST Node
name	CDATA #REQUIRED
title	CDATA #REQUIRED
typ	CDATA #IMPLIED
_oid	CDATA	#IMPLIED
>

<!ELEMENT Table (Column*, Row*)>
<!ATTLIST Table
name	CDATA #REQUIRED
type	CDATA	#REQUIRED
_oid	CDATA	#IMPLIED
>

<!ELEMENT Column EMPTY>
<!ATTLIST Column
name	CDATA	#REQUIRED
type	CDATA	#REQUIRED
>

<!ELEMENT Row (Component*)>
<!ATTLIST Row
editable	CDATA	#IMPLIED
inserted	CDATA	#IMPLIED
modified	CDATA	#IMPLIED
format	CDATA	#IMPLIED
_oid	CDATA	#IMPLIED
>

=== pkoeker-riser/guibuilder/GuiBuilder/release/samples/tutorial/BeispielTreeDaten.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE Panel SYSTEM 'guivalues.dtd'>

<Panel name="mainPanel">
  <Tree name="Music">
    <Node name="Music" title="Music">
      <Node name="Classic" title="Classic">
	<Node name="Beethoven" title="Beethoven" type="panel1.txt">
	  <Panel name="panel1">
	    <Component name="name1">Beethoven</Component>
	  </Panel>
	</Node>
	<Node name="Bach" title="Bach" type="panel1.txt">
	  <Panel name="panel1">
	    <Component name="name1">Bach</Component>
	  </Panel>
	</Node>
	<Node name="Mozart" title="Mozart" type="panel1.txt">
	  <Panel name="panel1">
	    <Component name="name1">Mozart</Component>
	  </Panel>
	</Node>
      </Node>
      <Node name="Pop" title="Pop">
	<Node name="Beatles" title="Beatles" type="panel2.txt">
	  <Panel name="panel2">
	    <Component name="telefon1">Bealtes</Component>
	    <Component name="privat">false</Component>
	  </Panel>
	</Node>
	<Node name="Cream" title="Cream" type="panel2.txt">
	  <Panel name="panel2">
	    <Component name="telefon1">Cream</Component>
	    <Component name="privat">true</Component>
	  </Panel>
	</Node>
	<Node name="Stones" title="Stones" type="panel2.txt">
	  <Panel name="panel2">
	    <Component name="telefon1">Stones</Component>
	    <Component name="privat">false</Component>
	  </Panel>
	</Node>
      </Node>
    </Node>
  </Tree>
</Panel>
