=== pkoeker-riser/guibuilder/eMaGuiBuilder/PLConfig.dtd
<!--
# Author: Peter Koeker
# Version: 0.8
# Date: 28.10.2006
-->
<!ENTITY % DatabaseType "(JDBC_ODBC | MYSQL | FIREBIRD | SQL_SERVER | MCKOI | MAXDB
| SYBASE | ORACLE | CACHE | DB2 | HSQLDB | POSTGRES)" >

<!ELEMENT Server (LayerName?, DatasetDefinitionFile?, Database+, Dataset?, Format?, 
Options?, (View | Statement | Batch)*)>

<!ELEMENT LayerName (#PCDATA)>
<!ELEMENT DatasetDefinitionFile (#PCDATA)>

<!ELEMENT Database (JDBC-Driver, (URL | DataSource), Catalog?, Schema?, 
Username?, Password?, MetadataTableTypes?,
MaxActiveConnections?, MaxIdleConnections?, MinIdleConnections?,
ConnectionTimeOut?, ValidationQuery?,
TransactionIsolationLevel?, Sequence*, PingStatement?, 
ReadMetaDataReferences?, ConvertBooleanValuesToInt?, 
OptimisticLockingField?, CreateUserField?, UpdateUserField? 
)
>
<!ATTLIST Database
name	NMTOKEN	#REQUIRED
enabled (true|false) #IMPLIED
>

<!ELEMENT JDBC-Driver (#PCDATA)>
<!ELEMENT URL (#PCDATA)>
<!ELEMENT DataSource (#PCDATA)>
<!ELEMENT Catalog (#PCDATA)>
<!ELEMENT Schema (#PCDATA)>
<!ELEMENT Username (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!-- "TABLE", "VIEW", "SYSTEM TABLE", "GLOBAL TEMPORARY", "LOCAL TEMPORARY", "ALIAS", "SYNONYM" -->
<!ELEMENT MetadataTableTypes (#PCDATA)>

<!ELEMENT Sequence (get, set?)>
<!ATTLIST Sequence
name NMTOKEN #IMPLIED
databaseType %DatabaseType; #IMPLIED
>

<!ELEMENT get (#PCDATA)>
<!ELEMENT set (#PCDATA)>

<!ELEMENT PingStatement (#PCDATA)>

<!ELEMENT TransactionIsolationLevel EMPTY>
<!ATTLIST TransactionIsolationLevel
value 
(TRANSACTION_NONE|
TRANSACTION_READ_COMMITTED|
TRANSACTION_READ_UNCOMMITTED|
TRANSACTION_REPEATABLE_READ|
TRANSACTION_SERIALIZABLE)
#REQUIRED>

<!ELEMENT Dataset (Encoding?, ElementName?)>
<!ELEMENT Encoding EMPTY>
<!ATTLIST Encoding
value CDATA #REQUIRED>

<!ELEMENT ElementName EMPTY>
<!ATTLIST ElementName
value CDATA #REQUIRED>

<!ELEMENT Format (DateFormat?, TimeFormat?, TimestampFormat?, DecimalFormat?)>
<!ELEMENT DateFormat EMPTY>
<!ATTLIST DateFormat
value CDATA #REQUIRED>

<!ELEMENT TimeFormat EMPTY>
<!ATTLIST TimeFormat
value CDATA #REQUIRED>

<!ELEMENT TimestampFormat EMPTY>
<!ATTLIST TimestampFormat
value CDATA #REQUIRED>

<!ELEMENT DecimalFormat EMPTY>
<!ATTLIST DecimalFormat
value CDATA #REQUIRED>

<!ELEMENT Options (Debug?)>
<!ELEMENT Debug EMPTY>
<!ATTLIST Debug
value (true|false) #REQUIRED>

<!ELEMENT ReadMetaDataReferences EMPTY>
<!ATTLIST ReadMetaDataReferences
value (true|false) #REQUIRED>

<!ELEMENT ConvertBooleanValuesToInt EMPTY>
<!ATTLIST ConvertBooleanValuesToInt
value (true|false) #REQUIRED>

<!ELEMENT OptimisticLockingField EMPTY>
<!ATTLIST OptimisticLockingField
value CDATA #REQUIRED>

<!ELEMENT CreateUserField EMPTY>
<!ATTLIST CreateUserField
value CDATA #REQUIRED>

<!ELEMENT UpdateUserField EMPTY>
<!ATTLIST UpdateUserField
value CDATA #REQUIRED>

<!ELEMENT TransactionWaitTimeout EMPTY>
<!ATTLIST TransactionWaitTimeout
value CDATA #REQUIRED>

<!ELEMENT MaxActiveConnections EMPTY>
<!ATTLIST MaxActiveConnections
value CDATA #REQUIRED>

<!ELEMENT MaxIdleConnections EMPTY>
<!ATTLIST MaxIdleConnections
value CDATA #REQUIRED>

<!ELEMENT MinIdleConnections EMPTY>
<!ATTLIST MinIdleConnections
value CDATA #REQUIRED>

<!ELEMENT ConnectionTimeOut EMPTY>
<!ATTLIST ConnectionTimeOut
value CDATA #REQUIRED>

<!ELEMENT ValidationQuery (#PCDATA)>

<!ELEMENT View (RootTable)>
<!ATTLIST View
name CDATA #REQUIRED
readonly (true|false) #IMPLIED
transient (true|false) #IMPLIED
database CDATA #IMPLIED
databaseType %DatabaseType; #IMPLIED
>

<!ELEMENT RootTable ((Column | Child | Parent)*)>
<!ATTLIST RootTable
tablename NMTOKEN #REQUIRED
viewname	CDATA	#IMPLIED
database CDATA #IMPLIED
distinct (true|false) #IMPLIED
pk CDATA #REQUIRED
alias CDATA #IMPLIED
where CDATA #IMPLIED
orderby CDATA #IMPLIED
groupby CDATA #IMPLIED
readonly (true|false) #IMPLIED
transient (true|false) #IMPLIED
fetchSize	CDATA	#IMPLIED
maxFieldSize	CDATA	#IMPLIED
maxRows	CDATA	#IMPLIED
queryTimeout	CDATA	#IMPLIED
databaseType %DatabaseType; #IMPLIED
>

<!ELEMENT Column EMPTY>
<!ATTLIST Column
name CDATA #REQUIRED
alias CDATA #IMPLIED
type (BIGINT|INTEGER|BOOLEAN|
CHAR|VARCHAR|
DECIMAL|NUMERIC|DOUBLE|
DATE|TIME|TIMESTAMP) #IMPLIED
notnull (true|false) #IMPLIED
size CDATA #IMPLIED
decimalDigits CDATA #IMPLIED
default CDATA #IMPLIED
readonly (true|false) #IMPLIED
transient (true|false) #IMPLIED
>

<!ELEMENT Child ((Column | Child | Parent)*)>
<!ATTLIST Child
tablename NMTOKEN #REQUIRED
refname CDATA #IMPLIED
viewname	CDATA	#IMPLIED
database CDATA #IMPLIED
distinct (true|false) #IMPLIED
pk CDATA #REQUIRED
fk CDATA #REQUIRED
alias CDATA #IMPLIED
attrib (true|false) #IMPLIED
selfReference (true|false) #IMPLIED
where CDATA #IMPLIED
orderby CDATA #IMPLIED
groupby CDATA #IMPLIED
readonly (true|false) #IMPLIED
transient (true|false) #IMPLIED
virtual NMTOKEN #IMPLIED
fetchSize	CDATA	#IMPLIED
maxFieldSize	CDATA	#IMPLIED
maxRows	CDATA	#IMPLIED
queryTimeout	CDATA	#IMPLIED
OnDelete (Cascade|SetNull|Restrict|NoAction|SetDefault) #IMPLIED
OnUpdate (Cascade|SetNull|Restrict|NoAction|SetDefault) #IMPLIED
databaseType %DatabaseType; #IMPLIED
>

<!ELEMENT Parent ((Column | Parent)*)>
<!ATTLIST Parent
tablename NMTOKEN #REQUIRED
viewname	CDATA	#IMPLIED
refname CDATA #IMPLIED
database CDATA #IMPLIED
pk CDATA #REQUIRED
fk CDATA #REQUIRED
alias CDATA #IMPLIED
join  CDATA #IMPLIED
transient (true|false) #IMPLIED
fetchSize	CDATA	#IMPLIED
maxFieldSize	CDATA	#IMPLIED
maxRows	CDATA	#IMPLIED
queryTimeout	CDATA	#IMPLIED
databaseType %DatabaseType; #IMPLIED
>

<!ELEMENT Statement (#PCDATA)>
<!ATTLIST Statement
name NMTOKEN #REQUIRED
maxRows CDATA #IMPLIED
datasetname NMTOKEN #IMPLIED
tablename NMTOKEN #IMPLIED
databaseType %DatabaseType; #IMPLIED
>

<!ELEMENT Batch (Statement*)>
<!ATTLIST Batch
name NMTOKEN #REQUIRED
>

=== pkoeker-riser/guibuilder/GuiBuilder/dbedit/PLConfig.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE Server SYSTEM '../PLConfig.dtd'>
<Server>
	<Database name="dbedit">
		<JDBC-Driver>org.hsqldb.jdbcDriver</JDBC-Driver>		
		<URL>jdbc:hsqldb:file:dbedit/dbedit</URL>
		<Username>sa</Username>
		<Password></Password>		
		<MaxActiveConnections value="3"/>
		<MinIdleConnections value="1"/>
		<Sequence>
			<get>SELECT NEXT VALUE FOR counter FROM information_schema.system_sequences</get>
		</Sequence>
		
		<OptimisticLockingField value="version" />		
	</Database>
	
	<Dataset> 
		<!-- Dataset Encoding; default is 'ISO-8859-1' -->
		<Encoding value='ISO-8859-1' />
		<!-- Name of Root Datset Element; default is 'Dataset' -->
		<ElementName value='DataSet' /> 
	</Dataset>
	<Format>
		<DateFormat value='dd.MM.yyyy' />
		<TimeFormat value='HH:mm' />
		<TimestampFormat value='dd.MM.yyyy HH:mm' />
		<DecimalFormat value="#0.00" />
	</Format>
	<Options>
		<Debug value="false" />
	</Options>
	<View name="Connection">
		<RootTable tablename="Connection" pk="ConnectionName" orderby="ConnectionName">
			<Column name="*" />
		</RootTable>
	</View>
	<View name="Request">
		<RootTable tablename="Request" pk="RequestId">
			<Column name="*" />
			<Child fk="fk_RequestId" tablename="TableRequest" refname="RootTables" pk="TableRequestId" where="RequestType = 1">
				<Column name="*" />
				<Child fk="fk_TableRequestId" tablename="TableColumn" 
					pk="ColumnId" orderby="DisplayOrder">
					<Column name="*" />
				</Child>
				<Child fk="fk_TableRequestId" tablename="TableRequest" refname="ChildTables" pk="TableRequestId" where="RequestType = 2">
					<Column name="*" />
					<Child fk="fk_TableRequestId" tablename="TableColumn" pk="ColumnId" orderby="DisplayOrder">
						<Column name="*" />
					</Child>
				</Child>
				<Child fk="fk_TableRequestId" tablename="TableRequest" refname="ParentTables" pk="TableRequestId" where="RequestType = 3">
					<Column name="*" />
					<Child fk="fk_TableRequestId" tablename="TableColumn" pk="ColumnId" orderby="DisplayOrder">
						<Column name="*" />
					</Child>
				</Child>
			</Child>
		</RootTable>
	</View>
	<View name="RequestOverview">
		<RootTable tablename="TableRequest" pk="TableRequestId" where="RequestType = 1" orderby="TableName">
			<Column name="*" />			
			<Parent join="true" tablename="Request" pk="RequestId" fk="fk_RequestId">
				<Column name="*" />
			</Parent>
			
		</RootTable>
	</View>
</Server>

=== pkoeker-riser/guibuilder/GuiBuilder/PLConfig.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE Server SYSTEM 'PLConfig.dtd'>
<Server>
	<DatasetDefinitionFile>DatabaseConfig.xml</DatasetDefinitionFile>
	<Database name="adresse" enabled="false">
		<!-- MySQL / Meta nur mit INNODB -->
		<JDBC-Driver>com.mysql.jdbc.Driver</JDBC-Driver>		
		<URL><![CDATA[jdbc:mysql://localhost/adresse?useUnicode=true&characterEncoding=iso-8859-1]]></URL>
		<Username></Username>
		<Password></Password>		
		<!-- Beim Hochfahren einzulesende Metadaten -->
		<MetadataTableTypes>TABLE|VIEW</MetadataTableTypes>
		<!-- Connection Pool -->
		<MaxActiveConnections value="20"/>
		<MaxIdleConnections value="20"/>
		<MinIdleConnections value="0"/>
		<ValidationQuery></ValidationQuery>
		<Sequence>
			<get>SELECT counter FROM counter WHERE oid = 1</get>
			<set>UPDATE counter SET counter = ? WHERE oid = 1</set>
		</Sequence>
		<OptimisticLockingField value="version" />
		<CreateUserField value="createUser" /> 
		<UpdateUserField value="updateUser" />
	</Database>
	<Database name="adresse" enabled="false">
		<!-- McKoi -->
		<JDBC-Driver>com.mckoi.JDBCDriver</JDBC-Driver>
		<URL>jdbc:mckoi:local://./db.conf</URL>
		<Schema>APP</Schema>
		<Username>peter</Username>
		<Password>peter</Password>
		<!-- Connection Pool -->
		<!-- defaults
		<MaxActiveConnections value="5"/>
		<MaxIdleConnections value="3"/>
		<MinIdleConnections value="0"/>
		-->
		<Sequence>
			<get>SELECT NEXTVAL('seq_counter')</get>
		</Sequence>
		<ConvertBooleanValuesToInt value="true" />
		<OptimisticLockingField value="version" />		
	</Database>
	<Database name="adresse" enabled="false">
		<!-- SQLServer/MSDE 2000 / Geht nicht mit MSDE7 -->
		<JDBC-Driver>com.microsoft.jdbc.sqlserver.SQLServerDriver</JDBC-Driver>
		<URL>jdbc:microsoft:sqlserver://localhost:1433;Databasename=adresse;SelectMethod=cursor</URL>
		<Username>sa</Username>
		<Password>peter</Password>
		<Sequence>
			<get>SELECT counter FROM sequence WHERE oid = 1</get>
			<set>UPDATE sequence SET counter = ? WHERE oid = 1</set>
		</Sequence>
		<ConvertBooleanValuesToInt value="true" />
		<OptimisticLockingField value="version" />		
	</Database>
	
	<Database name="adresse" enabled="false">
		<!-- JDBC/ODBC  / Meta geht nicht ! -->
		<JDBC-Driver>sun.jdbc.odbc.JdbcOdbcDriver</JDBC-Driver>
		<URL>jdbc:odbc:db2</URL>
		<Username>peter</Username>
		<Password>peter</Password>
		<Sequence>
			<get>SELECT counter FROM counter WHERE oid = 1</get>
			<set>UPDATE counter SET counter = ? WHERE oid = 1</set>
		</Sequence>
		<ConvertBooleanValuesToInt value="true" />
		<OptimisticLockingField value="version" />		
	</Database>

	<Database name="adresse" enabled="false">		
		<!-- Firebird / unterstützt keine Catalog -->
		<JDBC-Driver>org.firebirdsql.jdbc.FBDriver</JDBC-Driver>
		<URL>jdbc:firebirdsql:localhost/3050:E:/firebird/data/adresse.gdb</URL>
		<Username>sysdba</Username>
		<Password>masterkey</Password>
		<Sequence>
			<get>SELECT counter FROM counter WHERE oid = 1</get>
			<set>UPDATE counter SET counter = ? WHERE oid = 1</set>
		</Sequence>
		<ConvertBooleanValuesToInt value="true" />
		<OptimisticLockingField value="version" />		
	</Database>
	
	<Database name="adresse" enabled="false">
		<!-- Oracle -->
		<JDBC-Driver>oracle.jdbc.driver.OracleDriver</JDBC-Driver>
		<URL>jdbc:oracle:thin:@localhost:1521:peter</URL>
		<Schema>SYS</Schema>	
		<Username>peter</Username>
		<Password>peter</Password>	
		<Sequence>
			<get>SELECT seq_counter.NEXTVAL FROM DUAL</get>
		</Sequence>
		<ConvertBooleanValuesToInt value="true" />
		<OptimisticLockingField value="version" />		
	</Database>
	
	<Database name="adresse" enabled="false">	
		<!-- SAPDB Achtung! Der Dienst XSERVER muss gestartet werden! -->
		<!-- Bei SAP-DB gibt es eine Grenze von 8084 Bytes beim Lesen;
		das gilt nicht für LONG (=LONGVARCHAR);
		also statt varchar(2000) besser long verwenden! 
		Sonst gibts den Fehler: [-2003] Output columns too long -->
		<JDBC-Driver>com.sap.dbtech.jdbc.DriverSapDB</JDBC-Driver>
		<URL>jdbc:sapdb://peter/ADRESSE</URL>
		<Username>dba</Username>
		<Password>dba</Password>
		<Sequence>
			<get>select counter.nextval from dual</get>
		</Sequence>
		<ConvertBooleanValuesToInt value="true" />
		<OptimisticLockingField value="version" />		
	</Database>
	
	<Database name="adresse" enabled="false">
		<!-- SYBASE -->
		<JDBC-Driver>com.sybase.jdbc2.jdbc.SybDriver</JDBC-Driver>
		<URL>jdbc:sybase:Tds:localhost:2638</URL>
		<Schema>DBA</Schema>
		<Username>dba</Username>
		<Password>sql</Password>
		<Sequence>
			<get>SELECT counter FROM counter WHERE oid = 1</get>
			<set>UPDATE counter SET counter = ? WHERE oid = 1</set>
		</Sequence>
		<ConvertBooleanValuesToInt value="true" />
		<OptimisticLockingField value="version" />		
	</Database>
	
	<Database name="adresse" enabled="false">
		<!-- DB2 -->
		<JDBC-Driver>COM.ibm.db2.jdbc.net.DB2Driver</JDBC-Driver>
		<!--
		<JDBC-Driver>com.ibm.db2.jcc.DB2Driver</JDBC-Driver>
		-->
		<URL>jdbc:db2://localhost/adresse</URL>
		<Schema>PETER</Schema>
		<Username>peter</Username>
		<Password>peter2</Password>	
		<Sequence>
			<get>SELECT counter FROM counter WHERE oid = 1</get>
			<set>UPDATE counter SET counter = ? WHERE oid = 1</set>
		</Sequence>
		<ConvertBooleanValuesToInt value="true" />
		<OptimisticLockingField value="version" />		
	</Database>
	
	<Database name="adresse" enabled="false">
		<!-- Caché -->
		<JDBC-Driver>com.intersys.jdbc.CacheDriver</JDBC-Driver>
		<URL>jdbc:Cache://127.0.0.1:1972/USER</URL>
		<Username>_SYSTEM</Username>
		<Password>SYS</Password>
		<Sequence>
			<get>SELECT counter FROM counter WHERE oid = 1</get>
			<set>UPDATE counter SET counter = ? WHERE oid = 1</set>
		</Sequence>
		<!--
		<TransactionIsolationLevel value="TRANSACTION_SERIALIZABLE" />		
		<TransactionIsolationLevel value="TRANSACTION_READ_COMMITTED" />
		-->
		<ConvertBooleanValuesToInt value="true" />
		<OptimisticLockingField value="version" />		
	</Database>
	<Database name="adresse" enabled="false">
		<!-- AXION -->
		<JDBC-Driver>"org.axiondb.jdbc.AxionDriver</JDBC-Driver>
		<URL>jdbc:axiondb:adresse:axiondb</URL>
		<!--
		<Username>_SYSTEM</Username>
		<Password>SYS</Password>
		-->
		<Sequence>
			<get>SELECT counter FROM counter WHERE oid = 1</get>
			<set>UPDATE counter SET counter = ? WHERE oid = 1</set>
		</Sequence>
		<!--
		<TransactionIsolationLevel value="TRANSACTION_SERIALIZABLE" />		
		<TransactionIsolationLevel value="TRANSACTION_READ_COMMITTED" />
		-->
		<ConvertBooleanValuesToInt value="true" />
		<OptimisticLockingField value="version" />		
	</Database>
	
	<Dataset> 
		<!-- Dataset Encoding; default is 'ISO-8859-1' -->
		<Encoding value='ISO-8859-1' />
		<!-- Name of Root Datset Element; default is 'Dataset' -->
		<ElementName value='DataSet' /> 
	</Dataset>
	<Format>
		<DateFormat value='dd.MM.yyyy' />
		<TimeFormat value='HH:mm' />
		<TimestampFormat value='dd.MM.yyyy HH:mm:ss' />
		<DecimalFormat value="#0.00" />
	</Format>
	<Options>
		<Debug value="false" />
		<!--
		<CDataVARCHAR value="true" />
		-->
	</Options>
	<!-- GLUE -
	<WebService>
		<URL>http://localhost:8004</URL>
		<Service>pl</Service>
	</WebService>
	-->
	<!--
	<RMI>
		<Port>1099</Port>
		<Service>pl</Service>
	</RMI>
	-->
</Server>
